events {}
http {
    server {
        listen 8080;

        location /api/auth/ {
            proxy_pass http://auth-service:3001/;
        }
        location /api/citizen/ {
            proxy_pass http://citizen-service:3002/;
        }
        location /api/complaint/ {
            proxy_pass http://complaint-service:3003/;
        }
        location /api/notifications/ {
            proxy_pass http://notification-service:3004/;
        }
        location /api/monitoring/ {
            proxy_pass http://monitoring-service:3005/;
        }
        location / {
            proxy_pass http://frontend:3000/;
        }
    }
}
